version: "2"

services:

  mysql:
    image: mysql/mysql-server:5.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=idm
      - MYSQL_ROOT_HOST=%

  fiware-idm:
    image: fiware/idm:v5.4.0
    ports:
      - "8000:8000"
      - "5000:5000"
    environment:
      - DATABASE_HOST=mysql
