version: "2"
    
volumes:
  vol-mysql:

services:

  mysql:
    image: mysql/mysql-server:5.7.21
    ports:
      - "3306:3306"
    volumes:
      - vol-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=idm

  fiware-idm:
    image: fiware/idm:v5.4.0
    ports:
      - "8000:8000"
      - "5000:5000"
    environment:
      - DATABASE_HOST=mysql
